#!/usr/bin/env python3
"""Generates Sources/MatizKit/CountryLanguageDB.swift.

Combines two sources:
  - Google Cloud Translation's supported-language list, which defines WHICH
    languages the app offers (regional variants like es-MX are collapsed to
    their base language — the country dimension is handled by the app itself).
  - Unicode CLDR territoryInfo, which defines WHERE each language is commonly
    spoken: a language is linked to a country when it has official status
    (official, de-facto official, or official-regional) there, or is spoken by
    at least MIN_PERCENT of the population.

Country lists are ordered by estimated speaker count, descending, so the most
relevant country is the default in the UI.

Usage: tools/generate_db.py [cache_dir]
With cache_dir, source files are read from there if present and written there
after download.
"""

import json
import pathlib
import re
import sys
import urllib.request

CLDR = "https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json"
SOURCES = {
    "territoryInfo.json": f"{CLDR}/cldr-core/supplemental/territoryInfo.json",
    "territories.json": f"{CLDR}/cldr-localenames-full/main/en/territories.json",
    "languages.json": f"{CLDR}/cldr-localenames-full/main/en/languages.json",
    "google.html": "https://cloud.google.com/translate/docs/languages",
}

MIN_PERCENT = 15.0

# Google code -> CLDR code, for the handful that don't match mechanically.
ALIASES = {
    "zh-CN": "zh",
    "zh-TW": "zh-Hant",
    "iw": "he",
    "jw": "jv",
    "tl": "fil",
    "no": "nb",
}

# Nicer display names than CLDR's, where they differ.
NAME_OVERRIDES = {
    "zh": "Chinese (Simplified)",
    "zh-Hant": "Chinese (Traditional)",
    "nb": "Norwegian",
}

EXCLUDED_TERRITORIES = {"EU", "EZ", "UN", "QO", "ZZ", "XA", "XB"}


def load(name, cache_dir):
    if cache_dir:
        path = cache_dir / name
        if path.exists():
            return path.read_text()
    data = urllib.request.urlopen(SOURCES[name]).read().decode()
    if cache_dir:
        (cache_dir / name).write_text(data)
    return data


def normalize(code):
    """Collapse a Google language code to its CLDR base language."""
    if code in ALIASES:
        return ALIASES[code]
    parts = code.split("-")
    # strip region (es-MX) and script (bs-Cyrl, mni-Mtei) suffixes
    if len(parts) == 2 and re.fullmatch(r"[A-Z]{2}|[A-Z][a-z]{3}", parts[1]):
        return ALIASES.get(parts[0], parts[0])
    return code


def swift_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    cache_dir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else None

    territory_info = json.loads(load("territoryInfo.json", cache_dir))["supplemental"]["territoryInfo"]
    territory_names = json.loads(load("territories.json", cache_dir))["main"]["en"]["localeDisplayNames"]["territories"]
    language_names = json.loads(load("languages.json", cache_dir))["main"]["en"]["localeDisplayNames"]["languages"]
    google_html = load("google.html", cache_dir)

    raw_codes = set(re.findall(r"<code[^>]*>\s*([a-zA-Z][a-zA-Z-]{1,11})\s*</code>", google_html))
    languages = {}  # code -> name
    for raw in raw_codes:
        code = normalize(raw)
        name = NAME_OVERRIDES.get(code) or language_names.get(code)
        if name:  # anything without a CLDR English name is a stray <code> tag, not a language
            languages[code] = name
    if len(languages) < 100:
        sys.exit(f"only {len(languages)} languages extracted from Google's page — parsing is likely broken")

    # (language, country) -> estimated speakers
    speakers = {}
    for territory, info in territory_info.items():
        if len(territory) != 2 or territory in EXCLUDED_TERRITORIES or territory not in territory_names:
            continue
        population = float(info.get("_population", 0))
        for lang, stats in info.get("languagePopulation", {}).items():
            code = lang.replace("_", "-")
            if code not in languages:
                continue
            percent = float(stats.get("_populationPercent", 0))
            official = stats.get("_officialStatus") in ("official", "de_facto_official", "official_regional")
            if official or percent >= MIN_PERCENT:
                speakers[(code, territory)] = population * percent / 100

    countries_by_language = {}
    languages_by_country = {}
    for (code, territory), count in sorted(speakers.items(), key=lambda item: -item[1]):
        countries_by_language.setdefault(code, []).append(territory)
        languages_by_country.setdefault(territory, []).append(code)

    country_names = {t: territory_names[t] for t in languages_by_country}

    lines = []
    lines.append("// Generated by tools/generate_db.py — do not edit by hand.")
    lines.append("// Sources: Google Cloud Translation language list + Unicode CLDR territoryInfo.")
    lines.append("")
    lines.append("public enum CountryLanguageDB {")

    lines.append("    /// Languages supported by Google Translate, sorted by English name.")
    lines.append("    public static let languages: [Language] = [")
    for code, name in sorted(languages.items(), key=lambda item: item[1]):
        lines.append(f"        Language(code: {swift_str(code)}, name: {swift_str(name)}),")
    lines.append("    ]")
    lines.append("")

    lines.append("    /// English names of countries, keyed by ISO 3166-1 alpha-2 code.")
    lines.append("    public static let countryNames: [String: String] = [")
    for territory, name in sorted(country_names.items()):
        lines.append(f"        {swift_str(territory)}: {swift_str(name)},")
    lines.append("    ]")
    lines.append("")

    lines.append("    /// Countries where each language is commonly spoken, most speakers first.")
    lines.append("    public static let countriesByLanguage: [String: [String]] = [")
    for code in sorted(countries_by_language):
        entries = ", ".join(swift_str(t) for t in countries_by_language[code])
        lines.append(f"        {swift_str(code)}: [{entries}],")
    lines.append("    ]")
    lines.append("")

    lines.append("    /// Languages commonly spoken in each country, most speakers first.")
    lines.append("    public static let languagesByCountry: [String: [String]] = [")
    for territory in sorted(languages_by_country):
        entries = ", ".join(swift_str(c) for c in languages_by_country[territory])
        lines.append(f"        {swift_str(territory)}: [{entries}],")
    lines.append("    ]")
    lines.append("}")
    lines.append("")

    out = pathlib.Path(__file__).resolve().parent.parent / "Sources" / "MatizKit" / "CountryLanguageDB.swift"
    out.write_text("\n".join(lines))
    print(f"{out.name}: {len(languages)} languages, {len(country_names)} countries")


if __name__ == "__main__":
    main()
